
services:
  - type: web
    name: scan-cscan-visualizer
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run main.py --server.port=10000 --server.enableCORS=false"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
